os: linux
sudo: required

language: node_js
nodejs: "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1 
  - export PATH="$HOME/.yarn/bin:$PATH" 
  - ./install_deps.sh
  - . get_repo.sh
  - . setup_chroot.sh

cache:
  yarn: true

script:
  - ./build.sh

before_deploy:
  - export date=$(date +%s)
  - git config --local user.email "travis-ci@travis-ci.com"
  - git config --local user.name "Travis CI"
  - git tag "${date}-$(git log --format=%h -1)"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  name: $LATEST_MS_TAG-$date
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./*.tar.gz
    - vscode/.build/linux/deb/arm64/deb/*.deb
  on:
    all_branches: true
