matrix:
  include:
    - os: linux
      sudo: required

language: node_js
nodejs: "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1 
  - export PATH="$HOME/.yarn/bin:$PATH" 
  - ./install_deps.sh
  - . setup_chroot.sh
  - . get_repo.sh

cache:
  yarn: true

script:
  - ./build.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  name: $LATEST_MS_TAG
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - vscode/.build/linux/deb/arm64/deb/*.deb
  on:
    all_branches: true
