matrix:
  include:
    - os: linux
      sudo: required

language: node_js
nodejs: "8"

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.10.1-1
  - ./install_deps.sh
  - . get_repo.sh

cache:
  yarn: true

script:
  - ./build.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  name: $LATEST_MS_TAG
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - vscode/.build/linux/deb/arm64/deb/*.deb
  on:
    all_branches: true
